services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/src/app
      - /src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    ports:
      - 3001:3001
    stdin_open: true
    restart: always
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/src/app
      - /src/app/node_modules
    networks:
      - express-mongo
      - react-express

networks:
  react-express:
  express-mongo: